// resources/js/Pages/Auth/Login.vue
<script setup>
import Checkbox from '@/Components/Checkbox.vue';
import GuestLayout from '@/Layouts/GuestLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

defineProps({
  canResetPassword: {
    type: Boolean,
  },
  status: {
    type: String,
  },
});

const form = useForm({
  username: '',
  password: '',
  remember: false,
});

const submit = () => {
  form.post(route('login'), {
    onFinish: () => form.reset('password'),
  });
};
</script>

<template>
  <div class="soft-ui-box p-6">
    <h1>Login</h1>
    <form @submit.prevent="login">
      <div>
        <label for="username">Username</label>
        <input id="username" type="text" v-model="username" required autofocus>
      </div>

      <div>
        <label for="password">Password</label>
        <input id="password" type="password" v-model="password" required>
      </div>

      <div>
        <button type="submit">Login</button>
      </div>
    </form>
    <p>Don't have an account?</p>
    <p>
      Register <a :href="route('register')">Register</a>
    </p>
  </div>
</template>

<script>
export default {
  data() {
    return {
      username: '',
      password: '',
    };
  },
  methods: {
    login() {
      // Logic untuk mengirim data login menggunakan username dan password
      this.$inertia.post(route('login'), {
        username: this.username,
        password: this.password,
      });
    },
  },
};
</script>

<style src="login.css" lang="css" />

// resources/js/Pages/Auth/Login.jsx
import React, { useEffect } from 'react';
import Checkbox from '@/Components/Checkbox';
import GuestLayout from '@/Layouts/GuestLayout';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Head, Link, useForm } from '@inertiajs/react';
import './Login.css';


export default function Login({ status, canResetPassword }) {
    const { data, setData, post, processing, errors, reset } = useForm({
        username: '',
        password: '',
        remember: false,
    });

    useEffect(() => {
        return () => {
            reset('password');
        };
    }, []);

    const submit = (e) => {
        e.preventDefault();

        post(route('login'));
    };


    return (
        <GuestLayout>
            <div className="login-container">
                <div className="text-center mb-6">
                    <img src="../assets/img/astra.png" alt="Daihatsu Logo" className="mx-auto mb-2 login-logo" />
                </div>
                <h1 className="login-title">Login</h1>
                <form onSubmit={submit} className="login-form">
                    <div>
                        <InputLabel htmlFor="username" value="Username" />
                        <TextInput
                            id="username"
                            type="text" // Ganti dengan "text"
                            name="username"
                            value={data.username}
                            className="mt-1 block w-full"
                            autoComplete="username"
                            isFocused={true}
                            onChange={(e) => setData('username', e.target.value)}
                        />
                        <InputError message={errors.username} className="mt-2" />
                    </div>

                    <div className="mt-4">
                        <InputLabel htmlFor="password" value="Password" />
                        <TextInput
                            id="password"
                            type="password"
                            name="password"
                            value={data.password}
                            className="mt-1 block w-full"
                            autoComplete="current-password"
                            onChange={(e) => setData('password', e.target.value)}
                        />
                        <InputError message={errors.password} className="mt-2" />
                    </div>

                    <div className="block mt-4">
                        <label className="flex items-center">
                            <Checkbox
                                name="remember"
                                checked={data.remember}
                                onChange={(e) => setData('remember', e.target.checked)}
                            />
                            <span className="ml-2 text-sm text-gray-600">Remember me</span>
                        </label>
                    </div>

                    <div className="flex items-center justify-between mt-6">
                        <PrimaryButton className="login-button" disabled={processing}>
                            Log in
                        </PrimaryButton>
                    </div>
                    <div className="login-link-container">
                        Don't have an account?{' '}
                        <Link href={route('register')} className="login-link">
                            Register
                        </Link>
                    </div>
                </form>
            </div>
        </GuestLayout>
    );
}
